version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  user_backend:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: user_backend
    ports:
      - 8001:8001
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - MONGO_INITDB_DATABASE= mydatabase
      - JWT_SECRET=  AmiAmarSecretVuleJaiteParbeNaKonodin
volumes:
  data: