version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    env_file:
      - .env

  minioserver:
    image: minio/minio:latest
    container_name: minioserver
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: PCxCdQEu4JITZM6YQxjQ
      MINIO_SECRET_KEY: umpjR1npKAvAAQsQLiUcPYDsPeD7dAHCESJMQpE3
      MINIO_BUCKET_NAME: linkedin

  user_backend:
    build:
      context: ./user_backend
      dockerfile: Dockerfile
    container_name: user_backend
    ports:
      - 8001:8001
    volumes:
      - ./user_backend:/usr/src/app
    depends_on:
      - mongodb
    environment:
      - JWT_SECRET=AmiAmarSecretVuleJaiteParbeNaKonodin

  post_backend:
    build:
      context: ./post_backend
      dockerfile: Dockerfile
    container_name: post_backend
    ports:
      - 8002:8002
    volumes:
      - ./post_backend:/usr/src/app
    depends_on:
      - mongodb

  notification_backend:
    build:
      context: ./notification_backend
      dockerfile: Dockerfile
    container_name: notification_backend
    ports:
      - 8003:8003
    volumes:
      - ./notification_backend:/usr/src/app
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - user_backend
      - post_backend
      - notification_backend

volumes:
  mongodb:
  minio-data:
